export const DashboardCSS = {
    main: {
      display: "flex",
      minHeight: "80vh",
    },
    sideMain: {
        minWidth: "200px",
      height: "100vh",
      p: 1,
      position: 'sticky',
      left: 0,
      top: 0,
      boxSizing: 'border-box',
      overflowY: 'auto',
    },
    tabTitle: {
      m: 1,
      // py: 0,
      borderRadius: "10px",
      transition: "all 0.3s ease-in-out",
      textTransform: "capitalize",
      textAlign: "left",
      fontFamily: "Krona One",
      fontSize: "1rem",
      display: "flex",
      // height: "20px !important",
      justifyContent: "start",
      alignItems: "center",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "#304fa1",
        color: "#fff",
      },
    },
    tabActive: {
      backgroundColor: "#304fa1",
      color: "#fff !important",
    },
    tabIcon: {
      width: "30px",
      height: "30px",
      mr: "20px",
      ml: "5px",
    },
    mainProfileBox: {
      // flex: 2,
      // backgroundColor: "#f00",
      p: 3,
      width: "100%",
    },
    dataCard: {
      // backgroundColor: "#0f0",
      p: 2,
      display: "flex",
      justifyContent: "space-evenly",
      flexWrap: "wrap",
    },
    profileTitle: {
      fontFamily: "Krona One",
      color: "#304fa1",
    },
    profileCard: {
      height: "fit-content",
      flex: 1,
      // backgroundColor: "#00f",
      minWidth: "220px",
      m: 1,
      borderRadius: "20px",
      border: "1px solid #e6e6e6",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
    },
    detailCard: {
      flex: 2,
      m: 1,
      border: "1px solid #e6e6e6",
      // backgroundColor: "#ff0",
      borderRadius: "10px",
      overflow: "hidden",
      minWidth: "400px",
    },
    divider: {
      width: "100%",
      height: "1px",
      backgroundColor: "#e6e6e6",
      // margin: "10px 0",
      // padding: 2,
    },
    innerProfileCard: {
      padding: 3,
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
    },
    lowerProfile: {
      padding: 1,
      display: "flex",
      flexDirection: "column",
      // justifyContent: "center",
      // alignItems: "center",
      width: "100%",
    },
    uploadBtn: {
      width: "100%",
      px: 3,
      py: 1,
      borderRadius: "12px",
      backgroundColor: "#fff",
      textTransform: "capitalize",
      fontFamily: "Krona One",
      // border: "1px solid #304fa1",
      color: "#304fa1",
      "&:hover": {
        backgroundColor: "#304fa111",
        color: "#304fa1",
      },
    },
    detailTop: {
      p: 2,
      px: 3,
    },
    detailHead: {
      fontFamily: "Krona One",
      color: "#304fa1",
      fontSize: "1.5rem",
      // fontWeight: "bold",
      textTransform: "capitalize",
    },
    detailCaption: {
      fontFamily: "Krona One",
      color: "#304fa1",
      fontSize: "0.8rem",
      // fontWeight: "bold",
      textTransform: "capitalize",
    },
  
    detailMiddle: {
      p: 2,
      px: 3,
    },
    detailBottom: {
      display: "flex",
      justifyContent: "right",
      p: 2,
      px: 3,
    },
    detailBtn: {
      px: 3,
      py: 1,
      borderRadius: "12px",
      backgroundColor: "#304fa1",
      textTransform: "capitalize",
      fontFamily: "Krona One",
      border: "1px solid #304fa1",
      color: "#fff",
      "&:hover": {
        backgroundColor: "#fff",
        color: "#304fa1",
      },
    },
  };